import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, CalendarDays, Check, ChevronRight, ClipboardList, Download, FileText, ShieldCheck } from 'lucide-react';

const cameras = [
  { id: 'C3896', location: 'Westminster Bridge' },
  { id: 'C3897', location: 'Parliament Square' },
  { id: 'C3905', location: 'Victoria Street' },
];

const eventTypes = [
  { id: 'jaywalking', label: 'Jaywalking', color: '#ff4757' },
  { id: 'stopped', label: 'Stopped vehicle', color: '#f59e0b' },
  { id: 'risk', label: 'Elevated accident risk', color: '#fb7185' },
  { id: 'wrongWay', label: 'Wrong-way movement', color: '#65d0d9' },
];

const sampleCounts = {
  C3896: { jaywalking: 18, stopped: 2, risk: 4, wrongWay: 1 },
  C3897: { jaywalking: 17, stopped: 3, risk: 3, wrongWay: 2 },
  C3905: { jaywalking: 11, stopped: 1, risk: 2, wrongWay: 1 },
};

const stages = ['Compiling metrics…', 'Rendering charts…', 'Preparing PDF…'];
const panelStyle = { padding: '20px', background: 'rgba(20,22,30,0.62)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '8px', backdropFilter: 'blur(12px)' };
const labelStyle = { display: 'block', marginBottom: '8px', color: '#8b949e', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '10px', letterSpacing: '0.09em', textTransform: 'uppercase' };

const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
}[character]));

function createPrintableReport({ dateFrom, dateTo, selectedCameras, selectedEvents, totalEvents, perEvent }) {
  const rows = selectedEvents.map((event) => `<tr><td style="padding:10px;border-bottom:1px solid #d8dee8;color:#243044">${escapeHtml(event.label)}</td><td style="padding:10px;border-bottom:1px solid #d8dee8;text-align:right;font-family:monospace">${perEvent[event.id]}</td></tr>`).join('');
  const cameraRows = selectedCameras.map((camera) => `<li style="padding:5px 0;color:#334155">${escapeHtml(camera.id)} · ${escapeHtml(camera.location)}</li>`).join('');
  const period = `${escapeHtml(dateFrom)} to ${escapeHtml(dateTo)}`;

  return `<!doctype html><html><head><meta charset="utf-8"><title>MarsVision Executive Report</title></head><body style="margin:0;background:#eef2f7;color:#172033;font-family:Arial,sans-serif"><main style="max-width:900px;margin:30px auto;padding:48px;background:#fff;box-shadow:0 8px 30px rgba(15,23,42,.12)"><header style="padding-bottom:22px;border-bottom:3px solid #ff4757"><div style="color:#ff4757;font-family:monospace;font-size:12px;letter-spacing:2px">WESTMINSTER CV HACKATHON 2026 · MARS VISION</div><h1 style="margin:12px 0 6px;font-size:30px">Traffic Safety Executive Report</h1><div style="color:#64748b;font-size:13px">Analysis period: ${period}</div></header><section style="display:flex;gap:14px;margin:24px 0"><div style="flex:1;padding:16px;background:#f4f7fb;border-left:3px solid #3b82f6"><div style="color:#64748b;font-size:11px;text-transform:uppercase">Detected events</div><strong style="display:block;margin-top:8px;font-size:28px">${totalEvents}</strong></div><div style="flex:1;padding:16px;background:#f4f7fb;border-left:3px solid #ff4757"><div style="color:#64748b;font-size:11px;text-transform:uppercase">Camera feeds</div><strong style="display:block;margin-top:8px;font-size:28px">${selectedCameras.length}</strong></div><div style="flex:1;padding:16px;background:#f4f7fb;border-left:3px solid #35d39a"><div style="color:#64748b;font-size:11px;text-transform:uppercase">Event classes</div><strong style="display:block;margin-top:8px;font-size:28px">${selectedEvents.length}</strong></div></section><section style="display:flex;gap:40px"><div style="flex:1"><h2 style="font-size:16px">Event summary</h2><table style="width:100%;border-collapse:collapse"><thead><tr><th style="padding:10px;text-align:left;background:#f4f7fb">Event class</th><th style="padding:10px;text-align:right;background:#f4f7fb">Count</th></tr></thead><tbody>${rows}</tbody></table></div><div style="width:40%"><h2 style="font-size:16px">Included cameras</h2><ul style="padding-left:18px">${cameraRows}</ul><div style="margin-top:22px;padding:14px;background:#fff8ed;border:1px solid #f5d7a1;color:#704a10;font-size:12px;line-height:1.5">This report preview uses the MarsVision demonstration dataset. Validate detections against source footage before operational use.</div></div></section><footer style="margin-top:32px;padding-top:14px;border-top:1px solid #d8dee8;color:#64748b;font-family:monospace;font-size:10px">GENERATED BY MARSVISION · PART A EVENT DETECTION / PART B RISK ESTIMATION</footer></main></body></html>`;
}

export default function ReportGenerator() {
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [selectedCameraIds, setSelectedCameraIds] = useState(cameras.map((camera) => camera.id));
  const [selectedEventIds, setSelectedEventIds] = useState(eventTypes.map((event) => event.id));
  const [stageIndex, setStageIndex] = useState(-1);
  const [error, setError] = useState('');
  const isGenerating = stageIndex >= 0;

  const selectedCameras = useMemo(() => cameras.filter((camera) => selectedCameraIds.includes(camera.id)), [selectedCameraIds]);
  const selectedEvents = useMemo(() => eventTypes.filter((event) => selectedEventIds.includes(event.id)), [selectedEventIds]);
  const perEvent = useMemo(() => selectedEvents.reduce((totals, event) => {
    totals[event.id] = selectedCameras.reduce((sum, camera) => sum + sampleCounts[camera.id][event.id], 0);
    return totals;
  }, {}), [selectedCameras, selectedEvents]);
  const totalEvents = Object.values(perEvent).reduce((sum, count) => sum + count, 0);
  const invalidDates = Boolean(dateFrom && dateTo && dateFrom > dateTo);

  const toggleSelection = (selected, setSelected, value) => {
    setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);
  };

  const generateReport = async (event) => {
    event.preventDefault();
    setError('');
    if (!dateFrom || !dateTo || invalidDates) {
      setError('Choose a valid start and end date before generating the report.');
      return;
    }
    if (!selectedCameras.length || !selectedEvents.length) {
      setError('Select at least one camera and one event class.');
      return;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      setError('The report window was blocked. Allow pop-ups and try again.');
      return;
    }
    printWindow.document.write('<!doctype html><title>Preparing MarsVision report…</title><body style="background:#090d12;color:#e2e8f0;font-family:monospace;padding:40px">Preparing report…</body>');
    printWindow.document.close();

    setStageIndex(0);
    for (let index = 0; index < stages.length; index += 1) {
      setStageIndex(index);
      await new Promise((resolve) => window.setTimeout(resolve, 650));
    }

    printWindow.document.open();
    printWindow.document.write(createPrintableReport({ dateFrom, dateTo, selectedCameras, selectedEvents, totalEvents, perEvent }));
    printWindow.document.close();
    printWindow.opener = null;
    window.setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 350);
    setStageIndex(-1);
  };

  const inputStyle = { width: '100%', boxSizing: 'border-box', minHeight: '40px', padding: '8px 10px', color: '#e2e8f0', background: '#0c1016', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '5px', colorScheme: 'dark' };

  return (
    <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.42 }} style={{ display: 'flex', flexDirection: 'column', gap: '20px', color: '#e2e8f0' }}>
      <header style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '16px', flexWrap: 'wrap', paddingBottom: '16px', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '9px', color: '#8b949e', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '10px', letterSpacing: '0' }}><ClipboardList size={14} color="#65d0d9" /> OPERATIONS / REPORTING</div>
          <h1 style={{ margin: '9px 0 4px', color: '#e2e8f0', fontSize: '26px', fontWeight: 650 }}>Executive report</h1>
          <p style={{ color: '#8b949e', fontSize: '13px' }}>Configure the analysis scope and generate a print-ready PDF report.</p>
        </div>
        <div style={{ color: '#8b949e', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '10px' }}>DATASET / WESTMINSTER-2026</div>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 320px), 1fr))', gap: '18px', alignItems: 'start' }}>
        <form onSubmit={generateReport} style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          <motion.section variants={{ hidden: {}, show: { transition: { staggerChildren: 0.07 } } }} initial="hidden" animate="show" style={{ ...panelStyle, display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '9px', color: '#e2e8f0', fontSize: '13px', fontWeight: 700 }}><CalendarDays size={16} color="#65d0d9" /> 01 / Reporting period</div>
            <div className="report-date-fields" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <label><span style={labelStyle}>Start date</span><input required type="date" value={dateFrom} max={dateTo || undefined} onChange={(event) => setDateFrom(event.target.value)} style={inputStyle} /></label>
              <label><span style={labelStyle}>End date</span><input required type="date" value={dateTo} min={dateFrom || undefined} onChange={(event) => setDateTo(event.target.value)} style={inputStyle} /></label>
            </div>
          </motion.section>

          <section style={{ ...panelStyle, display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '9px', color: '#e2e8f0', fontSize: '13px', fontWeight: 700 }}><ShieldCheck size={16} color="#65d0d9" /> 02 / Camera sources</div>
            {cameras.map((camera) => {
              const checked = selectedCameraIds.includes(camera.id);
              return (
                <label key={camera.id} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', padding: '8px', background: checked ? 'rgba(101,208,217,0.08)' : 'transparent', border: `1px solid ${checked ? 'rgba(101,208,217,0.2)' : 'transparent'}`, borderRadius: '5px' }}>
                  <input type="checkbox" checked={checked} onChange={() => toggleSelection(selectedCameraIds, setSelectedCameraIds, camera.id)} style={{ accentColor: '#65d0d9', width: '15px', height: '15px' }} />
                  <span style={{ color: '#e2e8f0', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '12px' }}>{camera.id}</span>
                  <span style={{ marginLeft: 'auto', color: '#8b949e', fontSize: '11px' }}>{camera.location}</span>
                </label>
              );
            })}
          </section>

          <section style={{ ...panelStyle, display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '9px', color: '#e2e8f0', fontSize: '13px', fontWeight: 700 }}><AlertTriangle size={16} color="#ff4757" /> 03 / Event classes</div>
            {eventTypes.map((eventType) => {
              const checked = selectedEventIds.includes(eventType.id);
              return (
                <label key={eventType.id} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', padding: '7px 8px' }}>
                  <input type="checkbox" checked={checked} onChange={() => toggleSelection(selectedEventIds, setSelectedEventIds, eventType.id)} style={{ accentColor: eventType.color, width: '15px', height: '15px' }} />
                  <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: eventType.color }} />
                  <span style={{ color: '#cbd5e1', fontSize: '12px' }}>{eventType.label}</span>
                  <span style={{ marginLeft: 'auto', color: '#8b949e', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '11px' }}>{perEvent[eventType.id] ?? 0}</span>
                </label>
              );
            })}
          </section>

          {(error || invalidDates) && <div role="alert" style={{ padding: '10px 12px', color: '#ff8b96', background: 'rgba(255,71,87,0.1)', border: '1px solid rgba(255,71,87,0.28)', borderRadius: '5px', fontSize: '12px' }}>{error || 'End date must be on or after the start date.'}</div>}
          <button type="submit" disabled={isGenerating} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '9px', minHeight: '46px', color: '#fff', background: isGenerating ? '#292126' : 'linear-gradient(100deg, #982e27, #e04b3b)', border: '1px solid rgba(255,128,104,0.42)', borderRadius: '6px', cursor: isGenerating ? 'wait' : 'pointer', fontSize: '13px', fontWeight: 700 }}>
            {isGenerating ? <><motion.span animate={{ rotate: 360 }} transition={{ duration: 1.2, repeat: Infinity, ease: 'linear' }} style={{ display: 'inline-flex' }}><Download size={16} /></motion.span>{stages[stageIndex]}</> : <><FileText size={16} /> Generate PDF <ChevronRight size={15} /></>}
          </button>
          <div style={{ textAlign: 'center', color: '#657080', fontSize: '10px' }}>Opens a print-ready report. Choose “Save as PDF” in the print dialog.</div>
        </form>

        <motion.section initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.45, delay: 0.08 }} aria-label="Report preview" style={{ ...panelStyle, padding: '0', overflow: 'hidden' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '13px 16px', borderBottom: '1px solid rgba(255,255,255,0.08)', background: 'rgba(0,0,0,0.16)' }}>
            <span style={{ color: '#8b949e', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '10px', letterSpacing: '0.08em' }}>DOCUMENT PREVIEW</span>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', color: '#35d39a', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '9px' }}><Check size={12} /> READY</span>
          </div>
          <div style={{ margin: '18px auto', width: 'min(92%, 640px)', minHeight: '480px', boxSizing: 'border-box', padding: 'clamp(18px, 4vw, 34px)', color: '#1e293b', background: '#f8fafc', boxShadow: '0 8px 24px rgba(0,0,0,0.24)' }}>
            <div style={{ paddingBottom: '14px', borderBottom: '3px solid #ff4757' }}>
              <div style={{ color: '#ff4757', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '9px', letterSpacing: '0.1em' }}>WESTMINSTER CV HACKATHON 2026</div>
              <h2 style={{ margin: '9px 0 5px', color: '#172033', fontSize: 'clamp(17px, 3vw, 23px)' }}>Traffic Safety Executive Report</h2>
              <div style={{ color: '#64748b', fontSize: '10px' }}>{dateFrom || 'Start date'} — {dateTo || 'End date'}</div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '8px', margin: '18px 0' }}>
              {[
                { label: 'Events', value: totalEvents, color: '#65d0d9' },
                { label: 'Cameras', value: selectedCameras.length, color: '#ff4757' },
                { label: 'Classes', value: selectedEvents.length, color: '#35a982' },
              ].map((metric) => (
                <div key={metric.label} style={{ padding: '10px 8px', background: '#eef2f7', borderTop: `2px solid ${metric.color}` }}>
                  <div style={{ color: '#64748b', fontSize: '8px', textTransform: 'uppercase' }}>{metric.label}</div>
                  <div style={{ marginTop: '4px', color: '#172033', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '20px', fontWeight: 700 }}>{metric.value}</div>
                </div>
              ))}
            </div>
            <div style={{ color: '#334155', fontSize: '10px', fontWeight: 700, marginBottom: '8px' }}>Event distribution</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '9px' }}>
              {selectedEvents.map((eventType) => {
                const maxCount = Math.max(...Object.values(perEvent), 1);
                const count = perEvent[eventType.id] ?? 0;
                return (
                  <div key={eventType.id} style={{ display: 'grid', gridTemplateColumns: 'minmax(95px, 0.8fr) 1.5fr 28px', alignItems: 'center', gap: '8px' }}>
                    <span style={{ color: '#475569', fontSize: '9px' }}>{eventType.label}</span>
                    <span style={{ height: '7px', overflow: 'hidden', background: '#e2e8f0', borderRadius: '4px' }}><span style={{ display: 'block', width: `${count / maxCount * 100}%`, height: '100%', background: eventType.color, borderRadius: '4px' }} /></span>
                    <span style={{ color: '#334155', textAlign: 'right', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '9px' }}>{count}</span>
                  </div>
                );
              })}
              {!selectedEvents.length && <div style={{ padding: '18px', color: '#64748b', textAlign: 'center', fontSize: '10px' }}>Select event classes to populate this report.</div>}
            </div>
            <div style={{ marginTop: '20px', padding: '10px', color: '#704a10', background: '#fff8ed', border: '1px solid #f5d7a1', fontSize: '9px', lineHeight: 1.5 }}>Demonstration dataset preview. Validate detections against source footage before operational use.</div>
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: '8px', marginTop: '22px', paddingTop: '9px', borderTop: '1px solid #d8dee8', color: '#64748b', fontFamily: 'ui-monospace, Consolas, monospace', fontSize: '8px' }}><span>MARSVISION / PART A + PART B</span><span>1 / 1</span></div>
          </div>
        </motion.section>
      </div>
    </motion.div>
  );
}
